[phases.setup]
nixPkgs = ["tesseract", "poppler_utils", "glib", "postgresql"]
aptPackages = ["tesseract-ocr", "libtesseract-dev", "poppler-utils"]

[phases.build]
dependsOn = ["setup"]
cmds = ["pip install -r requirements.txt"]
